//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Option
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string CODE { get; set; }
        public string UNIT { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
