//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Products
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> ID_BRAND { get; set; }
        public Nullable<int> ID_CATEGORY { get; set; }
        public Nullable<int> ID_PROPERTIES { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ID_EMPLOYEE { get; set; }
        public byte[] CREATE_AT { get; set; }
    }
}
