//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Supplier
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string PHONE { get; set; }
        public string TAX { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public string ADDRESS { get; set; }
        public string NOTE { get; set; }
        public string NAME_ACCOUNT { get; set; }
        public string NUMBER_BANK { get; set; }
        public string NAME_BANK { get; set; }
        public string BRANCH_BANK { get; set; }
        public string CODE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_AT { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public string ID_CARD { get; set; }
    }
}
